name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - id: install-deps
        name: Install dependencies
        run: |
          npm install
      - id: test
        name: Run test
        run: |
          npm test
