name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - id: checkout
          name: Checkout
          uses: actions/checkout@v4
        - id: setup-node
          name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 22
        - id: install-deps
          name: Install dependencies
          run: |
            npm install
            npm install -g uglify-js shx
        - id: build
          name: Run build
          run: |
            npm run build
  